version: 2.1

orbs:
  # See the orb documentation here: https://circleci.com/developer/orbs/orb/circleci/node
  node: circleci/node@5.0.2

aliases:
  - &circleci_node
    - image: cimg/node:16.17.0

  - &current_workspace
    attach_workspace: { at: "." }

jobs:
  build-and-test:
    docker: *circleci_node
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Lint check
          command: yarn lint
      - run:
          name: Build lib
          command: yarn build
      - persist_to_workspace:
          root: "."
          paths:
            - "dist/*"
            - "node_modules/*"
  check-pr:
    docker: *circleci_node
    steps:
      - checkout
      - *current_workspace
      - run:
          name: Auto check PR
          command: yarn auto pr-check --url $CIRCLE_BUILD_URL
  publish-canary:
    docker: *circleci_node
    steps:
      - checkout
      - *current_workspace
      - run:
          name: Publish canary version
          command: yarn auto canary --target comment
  publish-latest:
    docker: *circleci_node
    steps:
      - checkout
      - *current_workspace
      - run:
          name: Publish latest version
          command: yarn auto latest --only-publish-with-release-label

workflows:
  build-test-deploy:
    jobs:
      - build-and-test
      - check-pr:
          filters:
            branches:
              ignore:
                - main
                - next
          requires:
            - build-and-test
      - publish-canary:
          filters:
            branches:
              ignore:
                - main
                - next
          requires:
            - build-and-test
            - check-pr
      - publish-latest:
          filters:
            branches:
              only: main
          requires:
            - build-and-test
